name: publish
on: [push]
env:
  IMAGE_NAME: postgres-backup 
jobs:
  publish-postgres-backup-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the postgres-backup Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          builder: ${{ steps.builder.outputs.name }}
          context: .
          push: true
          tags: ghcr.io/beatlang/postgres-backup:next


